# Generated by Django 5.0.1 on 2024-01-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('studentid', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('pass1', models.CharField(max_length=300)),
                ('course', models.CharField(max_length=300)),
                ('images', models.ImageField(upload_to='picture')),
            ],
        ),
    ]
